# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R-EdZEPEZtmSFI-MD-_LC_ZC6pL2bj0b

# **Matplotlib**

*   
Matplotlib, Python'da veri görselleştirme yapmak için kullanılan bir kütüphanedir. Çizgi grafikleri, sütun grafikleri, dağılım grafikleri, histogramlar ve daha birçok grafik türünü kolayca oluşturmak için kullanılır.
"""

import pandas as pd
veri = pd.read_csv("Iris.csv")
veri

veri.head()

veri.tail()

from google.colab import drive
drive.mount('/content/drive')

veri.columns

veri.info()

veri.describe()

import matplotlib.pyplot as plt

"""**Line Plot**"""

# x ekseni, y ekseni, color, alpha(opacity)
plt.figure(figsize=(6,2))
plt.plot(veri["Id"],veri["SepalLengthCm"], color = "red", alpha = 1, label = "SepalLengthCm") # line plot
plt.plot(veri["Id"],veri["PetalLengthCm"], color = "black", alpha = 1, label = "PetalLengthCm")
plt.title("İris Çiçeği Görselleştirme")
plt.xlabel("Id")
plt.ylabel("SepalLengthCm")
plt.grid(True)
plt.legend()
plt.show()

veri.Species.unique()

# Korelasyon, iki değişken arasındaki ilişkiyi ölçen bir kavramdır. İki değişkenin nasıl hareket ettiğini gösterir:

# Pozitif Korelasyon: Bir değişken artarken diğeri de artar.
# Negatif Korelasyon: Bir değişken artarken diğeri azalır.
# Korelasyon Yok: Değişkenler arasında ilişki yoktur.
plt.figure(figsize=(6,2))
plt.scatter(veri["SepalLengthCm"], veri["PetalLengthCm"], color = "red", s = 15, alpha = 0.7, label = 1)
plt.title("İris Çiçeği Görselleştirme")
plt.xlabel("SepalLengthCm")
plt.ylabel("PetalLengthCm")
plt.grid(True)
plt.legend()
plt.show()

veri.Species.unique()

veri_setosa = veri[veri.Species == 'Iris-setosa']
veri_versicolor = veri[veri.Species == 'Iris-versicolor']
veri_virginica = veri[veri.Species == 'Iris-virginica']

plt.figure(figsize = (6,2))
# scatter(x,y,renk,size, saydamlik)
plt.scatter(veri_setosa["SepalLengthCm"], veri_setosa["PetalLengthCm"], color = "black", s = 15, alpha = 0.7, label = "veri_setosa")
plt.scatter(veri_versicolor["SepalLengthCm"], veri_versicolor["PetalLengthCm"], color = "red", s = 15, alpha = 0.7, label = "veri_versicolor")
plt.scatter(veri_virginica["SepalLengthCm"], veri_virginica["PetalLengthCm"], color = "blue", s = 15, alpha = 0.7, label = "veri_virginica")
plt.title("İris Çiçeği Görselleştirme")
plt.xlabel("SepalLengthCm")
plt.ylabel("PetalLengthCm")
plt.grid(True)
plt.legend()
plt.show()

"""
# Görev: Breast Cancer Dataset Analizi ve Görselleştirme

1. Dataseti indir: [Breast Cancer Dataset](https://github.com/prashant-kikani/breast-cancer-detection/blob/master/breast-cancer-data.csv)
2. Pandas ile veriyi import et
3. Temel veri analizi yap
4. Matplotlib ile line plot ve scatter plot oluştur
5. Özetle, matplotlib başlığı altında yaptığımız tüm işlemleri bu veri seti ile yap
"""
# data = pd.read_csv("breast-cancer-data.csv")
# data

